const ALLOWED_ORIGIN = "https://adrxor.me";

function headers(origin=ALLOWED_ORIGIN){ return {"Access-Control-Allow-Origin": origin === ALLOWED_ORIGIN ? origin : ALLOWED_ORIGIN, "Access-Control-Allow-Headers":"Authorization, Content-Type", "Access-Control-Allow-Methods":"GET,POST,DELETE,OPTIONS", "Cache-Control":"no-store"}; }
function json(data,status=200){ return new Response(JSON.stringify(data),{status,headers:{"Content-Type":"application/json",...headers()}}); }
function slugify(s){ return String(s).toLowerCase().trim().replace(/[^a-z0-9\s-]/g,'').replace(/\s+/g,'-').replace(/-+/g,'-').slice(0,90) || `item-${Date.now()}`; }
function authorized(req,env){ const h=req.headers.get('Authorization')||''; if(!h.startsWith('Basic ')) return false; try { const decoded=atob(h.slice(6)); const i=decoded.indexOf(':'); return i>0 && decoded.slice(0,i)===env.ADMIN_USER && decoded.slice(i+1)===env.ADMIN_PASS; } catch { return false; } }
function requireAuth(req,env){ if(!authorized(req,env)) return new Response('Unauthorized',{status:401,headers:{'WWW-Authenticate':'Basic realm="adrxor admin"',...headers()}}); }

export default {async fetch(req,env){
  const url=new URL(req.url);
  if(req.method==='OPTIONS') return new Response(null,{headers:headers(req.headers.get('Origin'))});
  if(url.pathname==='/api/health') return json({ok:true});

  if(url.pathname.startsWith('/api/') && ['POST','DELETE'].includes(req.method)){ const denied=requireAuth(req,env); if(denied) return denied; }

  if(url.pathname==='/api/research' && req.method==='GET'){ const {results}=await env.DB.prepare('SELECT id,title,slug,description,tags,created_at,file_name, '/media/research/'||file_key AS file_url FROM research ORDER BY created_at DESC').all(); return json({items:results.map(x=>({...x,tags:JSON.parse(x.tags||'[]')}))}); }
  if(url.pathname==='/api/research' && req.method==='POST'){ const f=await req.formData(); const file=f.get('file'); if(!(file instanceof File) || file.type!=='application/pdf') return json({error:'PDF required'},400); if(file.size>100*1024*1024) return json({error:'Maximum file size is 100 MB'},400); const title=String(f.get('title')||'').trim(); if(!title) return json({error:'Title required'},400); const slug=slugify(String(f.get('slug')||title)); const key=`${slug}-${Date.now()}.pdf`; await env.MEDIA.put(`research/${key}`,file.stream(),{httpMetadata:{contentType:'application/pdf',cacheControl:'public, max-age=31536000, immutable'}}); const tags=JSON.stringify(String(f.get('tags')||'').split(',').map(x=>x.trim()).filter(Boolean)); try { await env.DB.prepare('INSERT INTO research(title,slug,description,tags,file_key,file_name,created_at) VALUES(?,?,?,?,?,?,?)').bind(title,slug,String(f.get('description')||''),tags,key,file.name,new Date().toISOString()).run(); } catch(e){ await env.MEDIA.delete(`research/${key}`); return json({error:'Slug already exists or database error'},409); } return json({ok:true,slug}); }

  if(url.pathname==='/api/posts' && req.method==='GET'){ const {results}=await env.DB.prepare('SELECT id,title,slug,excerpt,tags,content,published,created_at,published_at FROM posts ORDER BY created_at DESC').all(); return json({items:results.map(x=>({...x,published:Boolean(x.published),tags:JSON.parse(x.tags||'[]')}))}); }
  if(url.pathname==='/api/posts' && req.method==='POST'){ const b=await req.json(); const title=String(b.title||'').trim(), content=String(b.content||''); if(!title||!content) return json({error:'Title and content required'},400); const slug=slugify(String(b.slug||title)); const now=new Date().toISOString(), pub=b.published?1:0; try{await env.DB.prepare('INSERT INTO posts(title,slug,excerpt,tags,content,published,created_at,published_at) VALUES(?,?,?,?,?,?,?,?)').bind(title,slug,String(b.excerpt||''),JSON.stringify(b.tags||[]),content,pub,now,pub?now:null).run()}catch(e){return json({error:'Slug already exists or database error'},409)} return json({ok:true,slug}); }

  if(url.pathname==='/api/podcast' && req.method==='POST'){ const f=await req.formData(); const file=f.get('file'); if(!(file instanceof File) || !['audio/mpeg','audio/mp4','audio/wav','audio/x-wav'].includes(file.type) && !/\.(mp3|m4a|wav)$/i.test(file.name)) return json({error:'MP3, M4A or WAV required'},400); if(file.size>100*1024*1024) return json({error:'Maximum file size is 100 MB'},400); const title=String(f.get('title')||'').trim(); if(!title) return json({error:'Title required'},400); const key=`${slugify(title)}-${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'')}`; await env.MEDIA.put(`podcast/${key}`,file.stream(),{httpMetadata:{contentType:file.type||'audio/mpeg'}}); await env.DB.prepare('INSERT INTO podcast(title,description,episode,file_key,file_name,created_at) VALUES(?,?,?,?,?,?)').bind(title,String(f.get('description')||''),String(f.get('episode')||''),key,file.name,new Date().toISOString()).run(); return json({ok:true}); }

  if(url.pathname.startsWith('/media/')){ const key=url.pathname.slice('/media/'.length); const obj=await env.MEDIA.get(key); if(!obj) return new Response('Not found',{status:404,headers:headers()}); const h=new Headers(headers()); h.set('Content-Type',obj.httpMetadata?.contentType||'application/octet-stream'); h.set('Cache-Control','public, max-age=31536000, immutable'); return new Response(obj.body,{headers:h}); }
  return json({error:'Not found'},404);
}};
