name = "adrxor-api"
main = "src/index.js"
compatibility_date = "2026-09-02"

[[d1_databases]]
binding = "DB"
database_name = "adrxor"
database_id = "da836168-99dc-47b1-9068-eb4b478f581d"
migrations_dir = "migrations"
